development:
  adapter: postgresql
  encoding: unicode
  database: car-listing_development
  pool: 5
  username:
  password:


test:
  adapter: postgresql
  encoding: unicode
  database: car-listing_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: car-listing_production
  pool: 5
  username:
  password:
